name: Manual VisualCrossing History (extended data)

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  fetch-history:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # ČIA PAŠALINOME --no-cache-dir
      - name: Install requests
        run: pip install requests

      - name: Fetch historical data
        env:
          VC_API_KEY: ${{ secrets.VC_API_KEY }}
        run: python history_visualcrossing.py

      - name: Commit CSV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add history_visualcrossing.csv
          git commit -m "Extended VisualCrossing history 2025-05-24 to 2025-05-25" || echo "No changes"
          git push
